global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['localhost:6003']
    metrics_path: '/tam-metrics'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8098']